# 缩进使用空格，不用tab（制表符）
 spring:
   mvc:
     view:
          prefix: WEB-INF/jsp/
          suffix: .jsp

   datasource:
      url: jdbc:mysql://127.0.0.1/blog?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
      
 #springboot的文件上传默认开启
 
 
   resources:
     staticLocation:file:e:/upload/
 
   mail:
     #邮箱服务器地址
     host: smtp.qq.com
     #用户名
     username: 961977096@qq.com
     #发送密码
     password: 
     default-encoding: UTF-8
 
 # 日志配置
   loging:
    level:
     com:
       yc:
         blog:
           dao: debug
           web: warn
     
 #自定义属性以谁来发送邮件
   mail:
    fromMail:
     addr: 961977096@qq.com            